---
title: 'Notes on H. Naledi Analysis: H. naledi'
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = TRUE,
               warning = FALSE,
               message = FALSE)

library(here)
library(plotly)
library(readr)
library(here)
library(tibble)
library(stringr)
library(purrr)
```

Assume that we have downloaded all the files from g-drive, let's check the H. naledi data

```{r}
# get list of the local data files that we prepared earlier
nested_df_of_pp_data <-  
  read_rds(here("analysis", "data", "derived-data", "nested_df_of_pp_data.rds"))

# read these into R, and assign names to each data frame
nested_df_of_pp_data_H_naledi <- 
  nested_df_of_pp_data %>% 
  filter(str_detect(specimen, "naledi.*t2"))

# these landmarks need to be renamed to NA
# homo_naledi_101-283_21-landmarks-t2.pp: 1, 2, 4, 15-18, 21
nested_df_of_pp_data_H_naledi[[2]][[2]] <- 
  nested_df_of_pp_data_H_naledi[[2]][[2]]  %>% 
  mutate(x = ifelse(landmark %in% c(1, 2, 4, 15:18, 21), NA_integer_, x)) %>% 
  mutate(y = ifelse(landmark %in% c(1, 2, 4, 15:18, 21), NA_integer_, y)) %>% 
  mutate(z = ifelse(landmark %in% c(1, 2, 4, 15:18, 21), NA_integer_, z)) 

nested_df_of_pp_data_H_naledi
# homo_naledi_101-1240_21-landmarks-t2.pp: 2-4, 7-21
nested_df_of_pp_data_H_naledi[[2]][[1]]
# homo_naledi_101-466_21-landmarks-t2.pp: 3-5, 15-21
nested_df_of_pp_data_H_naledi[[2]][[3]]


```

Let's try to look at all of them

```{r}
list_of_plots_H_naledi  <- 
nested_df_of_pp_data_H_naledi %>% 
  mutate(plotly = map2(data, specimen, 
                       ~plot_ly(.x,
         x = .x$x, 
         y = .x$y, 
         z = .x$z, 
         color = .x$landmark,
         marker = list(symbol = 'circle'), 
         text = ~paste0("landmark: ", .x$landmark)) %>%
         add_markers() %>% 
  layout(scene = list(xaxis=list(title = .y)))))

htmltools::tagList(list_of_plots_H_naledi$plotly)

```

